global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: obs-aggregator-demo
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
rule_files: []
scrape_configs:
- job_name: service-a
  static_configs:
  - targets:
    - service-a:8001
  metrics_path: /metrics
- job_name: service-b
  static_configs:
  - targets:
    - service-b:8002
  metrics_path: /metrics
- job_name: service-c
  static_configs:
  - targets:
    - service-c:8003
  metrics_path: /metrics
- job_name: node
  static_configs:
  - targets:
    - node-exporter:9100
  metrics_path: /metrics
- job_name: service-d
  static_configs:
  - targets:
    - service-d:8004
  metrics_path: /metrics
